name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit & integration tests
        run: npm run coverage

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: E2E tests
        run: npm run test:e2e -- --reporter=html,github

      - name: A11y components
        run: npm run a11y:components

      - name: Build for preview
        run: npm run build

      - name: Lighthouse CI (PR only)
        if: github.event_name == 'pull_request'
        run: npm run perf

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            reports/**
            playwright-report/**
          if-no-files-found: ignore


